export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE"
//export const UPDATE_INGREDIENT_PRICE = "UPDATE_INGREDIENT_PRICE"

export const RESET_INGREDIENT = "RESET_INGREDIENT"

export const LOAD_ORDERS = "LOAD_ORDERS"
export const FAILED_LOAD_ORDERS="FAILED_LOAD_ORDERS"


