export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"

export const UPDATE_PURCHASABLE = "UPDATE_PURCHASABLE"
export const UPDATE_INGREDIENT_PRICE = "UPDATE_INGREDIENT_PRICE"